services:
  - type: web
    runtime: static
    name: voterizz
    repo: https://github.com/leonbrill3/voterizz
    branch: main
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
